import Head from "next/head";
import { SignedIn } from "@clerk/nextjs";

import type { ReactNode } from "react";

import Navbar from "@/components/common/Header/Navbar";
import Information from "@/components/common/Header/Information";
import Footer from "./Footer";

interface ILayoutProps {
  children: ReactNode;
}

const Layout = ({ children }: ILayoutProps) => {
  return (
    <>
      <Head>
        <title>Earth Doom - www.earthdoom.com</title>
        <meta name="description" content="Generated by Earth Doom" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <SignedIn>
        <Information />
      </SignedIn>
      <main className="flex items-center justify-center  lg:px-[5rem] 2xl:px-0">
        {children}
      </main>
      <Footer />
    </>
  );
};

export default Layout;
