export const PRODUCTION = [
  {
    buildingId: 1,
    buildingName: "Light infantry",
    buildingDescription:
      "Light infantry is a quick unit that is good for hit and run techniques. What it lacks in firepower, it makes up with it with his speed and agility.",
    buildingFieldName: "p_infinitys",
    buildingFieldNameETA: "p_infinitys_eta",
    buildingRequirement: "c_airport",
    buildingETA: 10,
    buildingCost: "300c",
    buildingCostCrystal: 300,
    buildingCostTitanium: 0,
  },
  {
    buildingId: 2,
    buildingName: "Shadow",
    buildingDescription:
      "Shadows are heavier versions of Light Infantry. Very good against Ares and Hellspawns.",
    buildingFieldName: "p_wraiths",
    buildingFieldNameETA: "p_wraiths_eta",
    buildingRequirement: "c_airport",
    buildingETA: 10,
    buildingCost: "300c",
    buildingCostCrystal: 300,
    buildingCostTitanium: 0,
  },
  {
    buildingId: 3,
    buildingName: "Heavy Infantry",
    buildingDescription:
      "Heavy Infantry is a slow but powerful unit that is good for frontal assaults.",
    buildingFieldName: "p_cobras",
    buildingFieldNameETA: "p_cobras_eta",
    buildingRequirement: "c_abase",
    buildingETA: 15,
    buildingCost: "500c",
    buildingCostCrystal: 500,
    buildingCostTitanium: 0,
  },
  {
    buildingId: 4,
    buildingName: "Goliaths",
    buildingDescription:
      "Using the latest in fusion powered propulsion systems and plasma cannons, the Goliath Tank provides the backbone of many armies.",
    buildingFieldName: "p_warfrigs",
    buildingFieldNameETA: "p_warfrigs_eta",
    buildingRequirement: "c_abase",
    buildingETA: 20,
    buildingCost: "1000c",
    buildingCostCrystal: 1000,
    buildingCostTitanium: 0,
  },
  {
    buildingId: 5,
    buildingName: "Grabber",
    buildingDescription:
      "The grabber is the only unit that can claim land in combat. Be sure to build many of those before attacking",
    buildingFieldName: "p_astropods",
    buildingFieldNameETA: "p_astropods_eta",
    buildingRequirement: "c_abase",
    buildingETA: 30,
    buildingCost: "1500c",
    buildingCostCrystal: 1500,
    buildingCostTitanium: 0,
  },
  {
    buildingId: 6,
    buildingName: "Hellspawns",
    buildingDescription:
      "The hellspawn class robot is a special type designed for combat. It is effective against Light Infantry and Goliath.",
    buildingFieldName: "p_destroyers",
    buildingFieldNameETA: "p_destroyers_eta",
    buildingRequirement: "c_destfact",
    buildingETA: 30,
    buildingCost: "1500c",
    buildingCostCrystal: 1500,
    buildingCostTitanium: 0,
  },
  {
    buildingId: 7,
    buildingName: "Reaper",
    buildingDescription:
      "The reaper cannon is a general purpose cannon which is extremely effective against grabbers and light units.",
    buildingFieldName: "p_rcannons",
    buildingFieldNameETA: "p_rcannons_eta",
    buildingRequirement: "c_odg",
    buildingETA: 30,
    buildingCost: "1500c",
    buildingCostCrystal: 1500,
    buildingCostTitanium: 0,
  },
  {
    buildingId: 8,
    buildingName: "Avengers",
    buildingDescription:
      "Using a mounted Tachyon Particle Disrupter, the avenger is effective against medium-sized units like the Goliath.",
    buildingFieldName: "p_avengers",
    buildingFieldNameETA: "p_avengers_eta",
    buildingRequirement: "c_odg",
    buildingETA: 30,
    buildingCost: "1500c",
    buildingCostCrystal: 1500,
    buildingCostTitanium: 0,
  },
  {
    buildingId: 9,
    buildingName: "Lucius",
    buildingDescription:
      "The Lucius are large slow firing cannons that use physical rounds instead of energy weapons.It is effective against the larger robots.",
    buildingFieldName: "p_lstalkers",
    buildingFieldNameETA: "p_lstalkers_eta",
    buildingRequirement: "c_odg",
    buildingETA: 30,
    buildingCost: "1500c",
    buildingCostCrystal: 1500,
    buildingCostTitanium: 0,
  },
];
