import type { Building } from "../types/types";

export const BUILDINGS: Building[] = [
  {
    buildingId: 1,
    buildingName: "Tax collectors",
    buildingDescription: "Automatically collects tax from civilians. Taxes generate credits which you need to produce units, do research and more.",
    buildingFieldName: "c_crystal",
    buildingETA: 10,
    buildingCost: "Free",
    buildingCostCrystal: 0,
    buildingCostTitanium: 0,
  },
  {
    buildingId: 2,
    buildingName: "Titanium extractor",
    buildingDescription: "Enables titanium extractor, which gives you titanium each tick. ",
    buildingFieldName: "c_metal",
    buildingETA: 20,
    buildingCost: "500c",
    buildingCostCrystal: 500,
    buildingCostTitanium: 0,
  },
  {
    buildingId: 3,
    buildingName: "Fusion power plant",
    buildingDescription: "Enables construction of fusion power plants, which generate energy.",
    buildingFieldName: "c_energy",
    buildingETA: 50,
    buildingCost: "5000c",
    buildingCostCrystal: 5000,
    buildingCostTitanium: 0,
  },
  {
    buildingId: 4,
    buildingName: "Barracks",
    buildingDescription: "Enables training of Light Infantry.",
    buildingFieldName: "c_airport",
    buildingETA: 20,
    buildingCost: "2500c 1000t",
    buildingCostCrystal: 2500,
    buildingCostTitanium: 1000,
  },
  {
    buildingId: 5,
    buildingName: "Robot Factory",
    buildingDescription: "Enables building of advanced robots.",
    buildingFieldName: "c_abase",
    buildingETA: 40,
    buildingCost: "5000c 3000t",
    buildingCostCrystal: 5000,
    buildingCostTitanium: 3000,
  },
  {
    buildingId: 6,
    buildingName: "Hellspawn factory",
    buildingDescription: "Enables building of Hellspawns.",
    buildingFieldName: "c_destfact",
    buildingETA: 120,
    buildingCost: "10000c 10000t",
    buildingCostCrystal: 10000,
    buildingCostTitanium: 10000,
  },
  {
    buildingId: 7,
    buildingName: "BDU factory",
    buildingDescription: "Enables building of Base Defence Units.",
    buildingFieldName: "c_odg",
    buildingETA: 120,
    buildingCost: "20000c 20000t",
    buildingCostCrystal: 20000,
    buildingCostTitanium: 20000,
  },
];
