import { useState, useEffect } from "react";

import { BsArrowLeft, BsArrowRight } from "react-icons/bs";

import { type NextPage } from "next";
import Head from "next/head";

import Navbar from "@/components/Header/Navbar";

const Country: NextPage = () => {
  // https://tailwind-elements.com/docs/standard/data/tables/

  const [myx, setMyx] = useState<number>(1);

  useEffect(() => {
    fetchData();
  }, [myx]);

  const fetchData = () => {
    if (!myx) return;
  };

  const handleChange = (event: { target: { value: string | number } }) => {
    const { value } = event.target;
    if (Number.isInteger(Number(value))) {
      setMyx(Number(value));
    }
  };

  const handlePrev = () => {
    setMyx(myx - 1);
  };

  const handleNext = () => {
    setMyx(myx + 1);
  };

  const mockData = [
    {
      id: 1,
      y: 10,
      tag: "Tag 1",
      nick: "Nick 1",
      commander: 1,
      score: 1000000,
      size: "Large",
      timer: Date.now(),
    },
    {
      id: 2,
      y: 20,
      tag: "Tag 2",
      nick: "Nick 2",
      commander: 2,
      score: 500000,
      size: "Medium",
      timer: Date.now() - 1000 * 60 * 10,
    },
    {
      id: 3,
      y: 30,
      tag: "Tag 3",
      nick: "Nick 3",
      commander: 3,
      score: 250000,
      size: "Small",
      timer: Date.now() - 1000 * 60 * 20,
    },
  ];

  return (
    <>
      <Head>
        <title>Earthdoom</title>
        <meta name="description" content="Generated by Earth Doom" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="min-h-screen bg-neutral-900">
        <div className="flex justify-center">
          <div className="my-6 mt-16">
            <button
              className="mr-2 rounded-lg bg-blue-500 px-4 py-2 text-white hover:bg-blue-700"
              onClick={handlePrev}
            >
              <BsArrowLeft className="mr-2 inline-block" />
              Previous
            </button>
            <input
              className="mr-2 rounded-lg border px-4 py-2"
              type="text"
              name="myx"
              size={5}
              maxLength={3}
              value={myx}
              onChange={handleChange}
            />
            <button
              className="rounded-lg bg-blue-500 px-4 py-2 text-white hover:bg-blue-700"
              onClick={handleNext}
            >
              Next
              <BsArrowRight className="ml-2 inline-block" />
            </button>
          </div>
        </div>

        <div className="my-6 flex justify-center">
          <img src="https://via.placeholder.com/150" alt="" />
          <p className="text-white">My Name (10) Score: 1000000</p>
        </div>

        <div className="flex items-center justify-center">
          <table className="table-auto border-collapse border border-gray-300 bg-white">
            <thead>
              <tr>
                <th className="px-4 py-2">Location:</th>
                <th className="px-4 py-2">ID :</th>
                <th className="px-4 py-2">Tag:</th>
                <th className="px-4 py-2">Nick:</th>
                <th className="px-4 py-2">Score:</th>
                <th className="px-4 py-2">Size:</th>
                <th className="px-4 py-2">Spying:</th>
              </tr>
            </thead>
            <tbody>
              {mockData.map((row) => (
                <tr
                  key={row.id}
                  className="border-b border-gray-300 hover:bg-gray-100"
                >
                  <td className="px-4 py-2">
                    <b>{row.y}</b>
                  </td>
                  <td className="px-4 py-2">
                    <b>{row.id}</b>
                  </td>
                  <td className="px-4 py-2">
                    <b>{row.tag}</b>
                  </td>
                  <td className="px-4 py-2">
                    <b>
                      <a href={`/communication?til=${row.id}`}>
                        <span
                          className={`text-${
                            row.commander === 1 ? "red" : "blue"
                          }`}
                        >
                          {row.nick}
                        </span>
                        {Date.now() - row.timer < 600000 && (
                          <span className="text-green-500"> (ONLINE)</span>
                        )}
                      </a>
                    </b>
                  </td>
                  <td className="px-4 py-2">
                    <b>{row.score.toString()}</b>
                  </td>
                  <td className="px-4 py-2">
                    <b>{row.size}</b>
                  </td>
                  <td className="px-4 py-2">
                    <a href={`/spy?id=${row.id}`}>Spy</a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="mt-8 flex flex-col bg-white">
          <div className="overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div className="inline-block min-w-full py-2 sm:px-6 lg:px-8">
              <div className="overflow-hidden">
                <table className="min-w-full text-left text-sm font-light">
                  <thead className="border-b font-medium dark:border-neutral-500">
                    <tr>
                      <th scope="col" className="px-6 py-4">
                        #
                      </th>
                      <th scope="col" className="px-6 py-4">
                        First
                      </th>
                      <th scope="col" className="px-6 py-4">
                        Last
                      </th>
                      <th scope="col" className="px-6 py-4">
                        Handle
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="border-b dark:border-neutral-500">
                      <td className="whitespace-nowrap px-6 py-4 font-medium">
                        1
                      </td>
                      <td className="whitespace-nowrap px-6 py-4">Mark</td>
                      <td className="whitespace-nowrap px-6 py-4">Otto</td>
                      <td className="whitespace-nowrap px-6 py-4">@mdo</td>
                    </tr>
                    <tr className="border-b dark:border-neutral-500">
                      <td className="whitespace-nowrap px-6 py-4 font-medium">
                        2
                      </td>
                      <td className="whitespace-nowrap px-6 py-4">Jacob</td>
                      <td className="whitespace-nowrap px-6 py-4">Thornton</td>
                      <td className="whitespace-nowrap px-6 py-4">@fat</td>
                    </tr>
                    <tr className="border-b dark:border-neutral-500">
                      <td className="whitespace-nowrap px-6 py-4 font-medium">
                        3
                      </td>
                      <td className="whitespace-nowrap px-6 py-4">Larry</td>
                      <td className="whitespace-nowrap px-6 py-4">Wild</td>
                      <td className="whitespace-nowrap px-6 py-4">@twitter</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-8 flex flex-col overflow-x-auto bg-white">
          <div className="sm:-mx-6 lg:-mx-8">
            <div className="inline-block min-w-full py-2 sm:px-6 lg:px-8">
              <div className="overflow-x-auto">
                <table className="min-w-full text-left text-sm font-light">
                  <thead className="border-b font-medium dark:border-neutral-500">
                    <tr>
                      <th scope="col" className="px-6 py-4">
                        #
                      </th>
                      <th scope="col" className="px-6 py-4">
                        Heading
                      </th>
                      <th scope="col" className="px-6 py-4">
                        Heading
                      </th>
                      <th scope="col" className="px-6 py-4">
                        Heading
                      </th>
                      <th scope="col" className="px-6 py-4">
                        Heading
                      </th>
                      <th scope="col" className="px-6 py-4">
                        Heading
                      </th>
                      <th scope="col" className="px-6 py-4">
                        Heading
                      </th>
                      <th scope="col" className="px-6 py-4">
                        Heading
                      </th>
                      <th scope="col" className="px-6 py-4">
                        Heading
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="border-b dark:border-neutral-500">
                      <td className="whitespace-nowrap px-6 py-4 font-medium">
                        1
                      </td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                    </tr>
                    <tr className="border-b dark:border-neutral-500">
                      <td className="whitespace-nowrap px-6 py-4 font-medium ">
                        2
                      </td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4 ">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4 ">Cell</td>
                    </tr>
                    <tr className="border-b ">
                      <td className="whitespace-nowrap px-6 py-4 font-medium ">
                        3
                      </td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                      <td className="whitespace-nowrap px-6 py-4">Cell</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Country;
