import { type NextPage } from "next";
import Head from "next/head";

import { SignIn } from "@clerk/nextjs";

import Navbar from "@/components/Header/Navbar";

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>Earthdoom</title>
        <meta name="description" content="Generated by Earth Doom" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex min-h-screen items-center justify-center bg-neutral-900">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="flex flex-col items-center gap-2">
            <SignIn path="/login" routing="path" signUpUrl="/login" />
          </div>
        </div>
      </main>
    </>
  );
};

export default Login;
