import { type NextPage } from "next";
import Head from "next/head";

import { SignIn, SignUp, useUser } from "@clerk/nextjs";

import { api } from "@/utils/api";

import Navbar from "@/components/Header/Navbar";
import SignOutButton from "@/components/Auth/SignOut";

const Register: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const user = useUser();

  return (
    <>
      <Head>
        <title>Earthdoom</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
              <br />
              {!user.isSignedIn && (
                <SignIn path="/login" routing="path" signUpUrl="/login" />
              )}
              {user.isSignedIn && <SignOutButton />}
              <br />
              <SignUp path="/register" routing="path" signInUrl="/register" />
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Register;
